#pragma once

#include "CreateInfoAutoGenerated.hxx"

#include <vk_mem_alloc.h>

template<>
struct CreateInfoFor<VmaAllocationCreateInfo> {
    static consteval VmaAllocationCreateInfo default_() {
        VmaAllocationCreateInfo ci{};
        return ci;
    }
};

template<>
struct CreateInfoFor<VkDebugUtilsMessengerCreateInfoEXT> {
    static consteval VkDebugUtilsMessengerCreateInfoEXT default_() {
        VkDebugUtilsMessengerCreateInfoEXT ci{};
        ci.sType = VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT;
        return ci;
    }
};

template<typename T>
[[nodiscard]] consteval T create_info() {
    return CreateInfoFor<T>::default_();
}
