#pragma once

#include "CreateInfoAutoGenerated.hxx"

#include <vk_mem_alloc.h>

template<>
struct CreateInfoFor<VmaAllocationCreateInfo> {
    static consteval VmaAllocationCreateInfo default_() {
        VmaAllocationCreateInfo ci{};
        return ci;
    }
};

template<typename T>
[[nodiscard]] consteval T create_info() {
    return CreateInfoFor<T>::default_();
}
