/**
 * tex_convert - Texture preprocessing tool for BindlessEngine
 *
 * Converts JPG/PNG → KTX2 (UASTC) using libktx directly.
 *
 * Format rules (evaluated in order):
 *   1. Normal map suffix (_ddn, _n, _normal, _nrm, _norm)
 *        → R8G8B8A8_UNORM, XY normals packed, ktxBasisParams::normalMap = true
 *   2. Source was JPG
 *        → R8G8B8A8_SRGB
 *   3. Source was PNG
 *        → R8G8B8A8_UNORM (linear)
 *
 * Mipmaps are generated by libktx during UASTC encoding (generateMipmaps = true).
 */

#ifdef _WIN32
#define NOMINMAX
#define WIN32_LEAN_AND_MEAN
#endif

#include <volk.h>

#include <ktx.h>
#include <ktxvulkan.h>

#include <Magick++.h>

#include <CLI/CLI.hpp>

#include <algorithm>
#include <atomic>
#include <cmath>
#include <filesystem>
#include <future>
#include <iostream>
#include <string>
#include <thread>
#include <vector>

namespace fs = std::filesystem;

static bool str_ends_with(std::string_view s, std::string_view suffix) {
    return s.size() >= suffix.size() && s.compare(s.size() - suffix.size(), suffix.size(), suffix) == 0;
}

static std::string stem_lower(const fs::path &p) {
    std::string s = p.stem().string();
    std::transform(s.begin(), s.end(), s.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    return s;
}

static bool is_normal_map(const fs::path &path) {
    const std::string stem = stem_lower(path);
    for (std::string_view suffix: {"_ddn", "_n", "_normal", "_nrm", "_norm"}) {
        if (str_ends_with(stem, suffix))
            return true;
    }
    return false;
}

enum class SourceKind { k_png, k_jpg };

struct SourceFile {
    fs::path path;
    fs::path orig_name;
    SourceKind kind;
};

struct ConvertResult {
    bool success;
    std::string message;
};

static ConvertResult convert_to_ktx2(const SourceFile &src, const fs::path &output_dir, bool normal_mode) {
    const std::string display_name = src.orig_name.filename().string();

    Magick::Image img;
    try {
        img.read(src.path.string());
        img.strip();
    } catch (const Magick::Exception &ex) {
        return {false, "  \u2717 " + display_name + ": " + ex.what()};
    }

    const uint32_t width = static_cast<uint32_t>(img.columns());
    const uint32_t height = static_cast<uint32_t>(img.rows());

    img.depth(8);
    Magick::Blob blob;
    img.write(&blob, "RGBA");
    const auto *raw = static_cast<const uint8_t *>(blob.data());

    const bool is_normal = is_normal_map(src.orig_name) && normal_mode;
    const bool is_srgb = (src.kind == SourceKind::k_jpg) && !is_normal;

    const size_t npixels = static_cast<size_t>(width) * height;
    std::vector<uint8_t> pixels(npixels * 4);

    if (is_normal) {
        for (size_t i = 0; i < npixels; ++i) {
            float x = (raw[i * 4 + 0] / 255.0f) * 2.0f - 1.0f;
            float y = (raw[i * 4 + 1] / 255.0f) * 2.0f - 1.0f;
            const float len = std::sqrt(x * x + y * y);
            if (len > 1e-6f) {
                x /= len;
                y /= len;
            }
            pixels[i * 4 + 0] = static_cast<uint8_t>(std::clamp((x * 0.5f + 0.5f) * 255.0f, 0.0f, 255.0f));
            pixels[i * 4 + 1] = static_cast<uint8_t>(std::clamp((y * 0.5f + 0.5f) * 255.0f, 0.0f, 255.0f));
            pixels[i * 4 + 2] = 0;
            pixels[i * 4 + 3] = 255;
        }
    } else {
        std::memcpy(pixels.data(), raw, npixels * 4);
    }

    const uint32_t vk_format = is_srgb ? VK_FORMAT_R8G8B8A8_SRGB : VK_FORMAT_R8G8B8A8_UNORM;

    ktxTextureCreateInfo tci{};
    tci.vkFormat = vk_format;
    tci.baseWidth = width;
    tci.baseHeight = height;
    tci.baseDepth = 1;
    tci.numDimensions = 2;
    tci.numLevels = 1;
    tci.numLayers = 1;
    tci.numFaces = 1;
    tci.isArray = KTX_FALSE;

    ktxTexture2 *ktx{};
    if (const auto err = ktxTexture2_Create(&tci, KTX_TEXTURE_CREATE_ALLOC_STORAGE, &ktx); err != KTX_SUCCESS) {
        return {false, "  \u2717 " + display_name + ": ktxTexture2_Create: " + ktxErrorString(err)};
    }

    if (const auto err = ktxTexture_SetImageFromMemory(ktxTexture(ktx), 0, 0, 0, pixels.data(), pixels.size());
        err != KTX_SUCCESS) {
        ktxTexture_Destroy(ktxTexture(ktx));
        return {false, "  \u2717 " + display_name + ": SetImageFromMemory: " + ktxErrorString(err)};
    }

    ktxBasisParams bp{};
    bp.structSize = sizeof(bp);
    bp.uastc = KTX_TRUE;
    bp.threadCount = 1; // file-level parallelism is handled outside
    bp.uastcFlags = KTX_PACK_UASTC_LEVEL_DEFAULT;
    bp.uastcRDO = KTX_FALSE;
    bp.normalMap = is_normal ? KTX_TRUE : KTX_FALSE;
    bp.noSSE = KTX_FALSE;
    bp.verbose = KTX_FALSE;

    if (const auto err = ktxTexture2_CompressBasisEx(ktx, &bp); err != KTX_SUCCESS) {
        ktxTexture_Destroy(ktxTexture(ktx));
        return {false, "  \u2717 " + display_name + ": CompressBasisEx: " + ktxErrorString(err)};
    }

    const fs::path out = output_dir / (src.orig_name.stem().string() + ".ktx2");
    if (const auto err = ktxTexture_WriteToNamedFile(ktxTexture(ktx), out.string().c_str()); err != KTX_SUCCESS) {
        ktxTexture_Destroy(ktxTexture(ktx));
        return {false, "  \u2717 " + display_name + ": WriteToNamedFile: " + ktxErrorString(err)};
    }

    ktxTexture_Destroy(ktxTexture(ktx));

    const char *fmt_desc = is_normal ? "normal map (UASTC)" : is_srgb ? "sRGB (UASTC)" : "linear (UASTC)";
    return {true, "  \u2713 " + display_name + " \u2192 " + out.filename().string() + " (" + fmt_desc + ")"};
}

struct JpgConvertResult {
    SourceFile source;
    std::string error;
};

static JpgConvertResult jpg_to_png(const fs::path &jpg_path, const fs::path &tmp_dir) {
    try {
        const fs::path out = tmp_dir / (jpg_path.stem().string() + ".png");
        Magick::Image img;
        img.read(jpg_path.string());
        img.strip();
        img.write(out.string());
        return {SourceFile{out, jpg_path, SourceKind::k_jpg}, {}};
    } catch (const Magick::Exception &ex) {
        return {{}, ex.what()};
    }
}

int main(int argc, char *argv[]) {
    Magick::InitializeMagick(*argv);

    CLI::App app{"tex_convert - JPG/PNG \u2192 KTX2 (UASTC) texture preprocessor"};

    fs::path input_dir;
    fs::path output_dir;
    uint32_t num_jobs = std::max(1u, std::thread::hardware_concurrency());
    bool normal_mode = true;

    app.add_option("input", input_dir, "Source directory containing JPG/PNG textures")->required();
    app.add_option("output", output_dir, "Destination directory for KTX2 files (defaults to input)");
    app.add_option("-j,--jobs", num_jobs, "Parallel file conversion jobs (default: CPU count)");
    app.add_flag("!--no-normal-mode", normal_mode,
                 "Disable normal map renormalization and UASTC normal-mode for detected normal maps");

    CLI11_PARSE(app, argc, argv);

    if (output_dir.empty())
        output_dir = input_dir;

    if (!fs::exists(input_dir) || !fs::is_directory(input_dir)) {
        std::cerr << "error: '" << input_dir << "' is not a valid directory\n";
        return 1;
    }

    fs::create_directories(output_dir);
    const fs::path tmp_dir = output_dir / ".tex_convert_tmp";
    fs::create_directories(tmp_dir);

    std::vector<fs::path> jpg_paths;
    std::vector<SourceFile> sources;

    for (const auto &entry: fs::directory_iterator(input_dir)) {
        if (!entry.is_regular_file())
            continue;
        std::string ext = entry.path().extension().string();
        std::transform(ext.begin(), ext.end(), ext.begin(),
                       [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
        if (ext == ".png") {
            sources.push_back({entry.path(), entry.path(), SourceKind::k_png});
        } else if (ext == ".jpg" || ext == ".jpeg") {
            jpg_paths.push_back(entry.path());
        }
    }

    std::cout << "input:       " << input_dir << '\n'
              << "output:      " << output_dir << '\n'
              << "jobs:        " << num_jobs << '\n'
              << "PNG files:   " << sources.size() << '\n'
              << "JPG files:   " << jpg_paths.size() << '\n'
              << "normal-mode: " << (normal_mode ? "on" : "off") << '\n'
              << '\n';

    std::atomic<uint32_t> success_count{0};
    std::atomic<uint32_t> failed_count{0};

    if (!jpg_paths.empty()) {
        std::cout << "[ JPG \u2192 PNG ]\n";

        std::vector<std::future<JpgConvertResult>> futures;
        futures.reserve(jpg_paths.size());
        for (const auto &jpg: jpg_paths) {
            futures.push_back(std::async(std::launch::async, jpg_to_png, jpg, tmp_dir));
        }

        for (size_t i = 0; i < futures.size(); ++i) {
            auto result = futures[i].get();
            if (result.error.empty()) {
                std::cout << "  \u2713 " << jpg_paths[i].filename() << " \u2192 " << result.source.path.filename()
                          << '\n';
                sources.push_back(std::move(result.source));
            } else {
                std::cerr << "  \u2717 " << jpg_paths[i].filename() << ": " << result.error << '\n';
                ++failed_count;
            }
        }
        std::cout << '\n';
    }

    if (!sources.empty()) {
        std::cout << "[ PNG \u2192 KTX2 ]\n";

        const size_t n = sources.size();
        for (size_t i = 0; i < n; i += num_jobs) {
            const size_t batch_end = std::min(i + static_cast<size_t>(num_jobs), n);
            std::vector<std::future<ConvertResult>> batch;
            batch.reserve(batch_end - i);

            for (size_t j = i; j < batch_end; ++j) {
                batch.push_back(std::async(std::launch::async,
                                           [&, j]() { return convert_to_ktx2(sources[j], output_dir, normal_mode); }));
            }

            for (auto &f: batch) {
                const auto result = f.get();
                std::cout << result.message << '\n';
                if (result.success)
                    ++success_count;
                else
                    ++failed_count;
            }
        }
    }

    fs::remove_all(tmp_dir);

    const uint32_t total = success_count + failed_count;
    std::cout << '\n'
              << "============================================================\n"
              << "done - " << success_count << '/' << total << " succeeded"
              << (failed_count > 0 ? ", " + std::to_string(failed_count) + " failed" : "") << '\n'
              << "============================================================\n";

    return failed_count > 0 ? 1 : 0;
}
