/**
 * tex_convert - Texture preprocessing tool for BindlessEngine
 *
 * Converts JPG/PNG → KTX2 (UASTC) using libktx directly.
 *
 * Format rules (evaluated in order):
 *   1. Normal map suffix (_ddn, _n, _normal, _nrm, _norm)
 *        → R8G8B8A8_UNORM, XY normals packed, ktxBasisParams::normalMap = true
 *   2. Source was JPG
 *        → R8G8B8A8_SRGB
 *   3. Source was PNG
 *        → R8G8B8A8_UNORM (linear)
 *
 * Mipmaps are generated by libktx during UASTC encoding (generateMipmaps = true).
 */

#include <cstring>
#include <lyra/arg.hpp>
#include <lyra/cli.hpp>
#include <lyra/help.hpp>
#include "Logger.hxx"
#ifdef _WIN32
#define NOMINMAX
#define WIN32_LEAN_AND_MEAN
#endif

#include <volk.h>

#include <ktx.h>
#include <ktxvulkan.h>

#include <Magick++.h>

#include <3PP/stb_image_resize2.h>
#include <algorithm>
#include <atomic>
#include <cmath>
#include <filesystem>
#include <future>
#include <string>
#include <thread>
#include <vector>

#include "LogFormatters.hxx"

namespace fs = std::filesystem;

static bool str_ends_with(std::string_view s, std::string_view suffix) {
    return s.size() >= suffix.size() && s.compare(s.size() - suffix.size(), suffix.size(), suffix) == 0;
}

static std::string stem_lower(const fs::path &p) {
    std::string s = p.stem().string();
    std::transform(s.begin(), s.end(), s.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    return s;
}

static bool is_normal_map(const fs::path &path) {
    const std::string stem = stem_lower(path);
    for (std::string_view suffix: {"_ddn", "_n", "_normal", "_nrm", "_norm"}) {
        if (str_ends_with(stem, suffix))
            return true;
    }
    return false;
}

static bool is_base_color(const fs::path &path) {
    const std::string stem = stem_lower(path);
    for (std::string_view suffix: {"_basecolor", "_base_color", "_albedo", "_diffuse"}) {
        if (str_ends_with(stem, suffix))
            return true;
    }
    return false;
}

enum class SourceKind { k_png, k_jpg };

struct SourceFile {
    fs::path path;
    fs::path orig_name;
    SourceKind kind;
};

// Returns true on success; logs info/error internally.
static bool convert_to_ktx2(const SourceFile &src, const fs::path &output_dir, bool normal_mode) {
    const std::string display_name = src.orig_name.filename().string();

    Magick::Image img;
    img.read(src.path.string());
    img.strip();

    const uint32_t width = static_cast<uint32_t>(img.columns());
    const uint32_t height = static_cast<uint32_t>(img.rows());

    img.depth(8);
    Magick::Blob blob;
    img.write(&blob, "RGBA");
    const auto *raw = static_cast<const uint8_t *>(blob.data());

    const bool is_normal = is_normal_map(src.orig_name) && normal_mode;
    const bool is_base_col = !is_normal && is_base_color(src.orig_name);
    const bool is_srgb = !is_normal && (is_base_col || src.kind == SourceKind::k_jpg);

    const char *fmt_desc = is_normal     ? "normal map (UASTC)"
                           : is_base_col ? "sRGB base color (UASTC)"
                           : is_srgb     ? "sRGB (UASTC)"
                                         : "linear (UASTC)";

    const size_t npixels = static_cast<size_t>(width) * height;
    std::vector<uint8_t> pixels(npixels * 4);
    std::memcpy(pixels.data(), raw, npixels * 4);

    const uint32_t mip_count =
            1u + static_cast<uint32_t>(std::floor(std::log2(static_cast<float>(std::max(width, height)))));

    std::vector<std::vector<uint8_t>> mip_chain;
    mip_chain.reserve(mip_count);
    mip_chain.push_back(pixels);

    for (uint32_t level = 1; level < mip_count; ++level) {
        const uint32_t sw = std::max(1u, width >> (level - 1));
        const uint32_t sh = std::max(1u, height >> (level - 1));
        const uint32_t dw = std::max(1u, sw / 2);
        const uint32_t dh = std::max(1u, sh / 2);

        std::vector<uint8_t> dst(dw * dh * 4);

        if (is_srgb) {
            stbir_resize_uint8_srgb(mip_chain[level - 1].data(), static_cast<int>(sw), static_cast<int>(sh), 0,
                                    dst.data(), static_cast<int>(dw), static_cast<int>(dh), 0, STBIR_RGBA);
        } else {
            stbir_resize_uint8_linear(mip_chain[level - 1].data(), static_cast<int>(sw), static_cast<int>(sh), 0,
                                      dst.data(), static_cast<int>(dw), static_cast<int>(dh), 0, STBIR_RGBA);
        }

        mip_chain.push_back(std::move(dst));
    }

    const uint32_t vk_format = is_srgb ? VK_FORMAT_R8G8B8A8_SRGB : VK_FORMAT_R8G8B8A8_UNORM;

    ktxTextureCreateInfo tci{};
    tci.vkFormat = vk_format;
    tci.baseWidth = width;
    tci.baseHeight = height;
    tci.baseDepth = 1;
    tci.numDimensions = 2;
    tci.numLevels = mip_count;
    tci.numLayers = 1;
    tci.numFaces = 1;
    tci.isArray = KTX_FALSE;

    ktxTexture2 *ktx{};
    if (const auto err = ktxTexture2_Create(&tci, KTX_TEXTURE_CREATE_ALLOC_STORAGE, &ktx); err != KTX_SUCCESS) {
        error("  [err] {}: ktxTexture2_Create: {}", display_name, ktxErrorString(err));
        return false;
    }

    for (uint32_t level = 0; level < mip_count; ++level) {
        if (const auto err = ktxTexture_SetImageFromMemory(ktxTexture(ktx), level, 0, 0, mip_chain[level].data(),
                                                           mip_chain[level].size());
            err != KTX_SUCCESS) {
            ktxTexture_Destroy(ktxTexture(ktx));
            error("  [err] {}: SetImageFromMemory level {}: {}", display_name, level, ktxErrorString(err));
            return false;
        }
    }

    ktxBasisParams bp{};
    bp.structSize = sizeof(bp);
    bp.uastc = KTX_TRUE;
    bp.threadCount = std::max(1u, std::thread::hardware_concurrency());
    bp.uastcFlags = KTX_PACK_UASTC_LEVEL_FASTEST;
    bp.uastcRDO = KTX_FALSE;
    bp.normalMap = is_normal ? KTX_TRUE : KTX_FALSE;
    bp.noSSE = KTX_FALSE;
    bp.verbose = KTX_FALSE;

    if (const auto err = ktxTexture2_CompressBasisEx(ktx, &bp); err != KTX_SUCCESS) {
        ktxTexture_Destroy(ktxTexture(ktx));
        error("  [err] {}: CompressBasisEx: {}", display_name, ktxErrorString(err));
        return false;
    }

    const fs::path out = output_dir / (src.orig_name.stem().string() + ".ktx2");
    if (const auto err = ktxTexture_WriteToNamedFile(ktxTexture(ktx), out.string().c_str()); err != KTX_SUCCESS) {
        ktxTexture_Destroy(ktxTexture(ktx));
        error("  [err] {}: WriteToNamedFile: {}", display_name, ktxErrorString(err));
        return false;
    }

    ktxTexture_Destroy(ktxTexture(ktx));

    info("  [ok] {} -> {} ({})", display_name, out.filename(), fmt_desc);
    return true;
}

struct JpgConvertResult {
    SourceFile source;
    std::string error_msg; // empty on successa
};

static JpgConvertResult jpg_to_png(const fs::path &jpg_path, const fs::path &tmp_dir) {
    const fs::path out = tmp_dir / (jpg_path.stem().string() + ".png");
    Magick::Image img;
    img.read(jpg_path.string());
    img.strip();
    img.write(out.string());
    return {SourceFile{out, jpg_path, SourceKind::k_jpg}, {}};
}

struct CLIOptions {
    fs::path input_dir;
    fs::path output_dir;
    uint32_t num_jobs = std::max(1u, std::thread::hardware_concurrency());
    bool normal_mode = true;
};

static auto parse_cli(int argc, char **argv) -> std::optional<CLIOptions> {
    CLIOptions opt{};
    bool show_help = false;
    std::string input_str;
    std::string output_str;

    auto cli = lyra::cli() | lyra::help(show_help) |
               lyra::arg(input_str, "input")("Source directory containing JPG/PNG textures").required() |
               lyra::opt(output_str,
                         "output")["--output"]["-o"]("Destination directory for KTX2 files (defaults to input)") |
               lyra::opt(opt.num_jobs, "jobs")["-j"]["--jobs"]("Parallel file conversion jobs (default: CPU count)") |
               lyra::opt([&](bool v) { opt.normal_mode = !v; }, "disable")["--no-normal-mode"](
                       "Disable normal map renormalization and UASTC normal-mode for detected normal maps");

    const auto result = cli.parse({argc, argv});

    if (show_help) {
        std::stringstream ss;
        ss << cli;
        info("Usage:\n{}", ss.str());
        return std::nullopt;
    }

    if (!result) {
        error("Argument error: {}", result.message());
        return std::nullopt;
    }

    opt.input_dir = input_str;

    if (!fs::exists(opt.input_dir) || !fs::is_directory(opt.input_dir)) {
        error("'{}' is not a valid directory", opt.input_dir);
        return std::nullopt;
    }

    opt.output_dir = output_str.empty() ? opt.input_dir : fs::path(output_str);

    if (opt.num_jobs < 1) {
        error("--jobs must be >= 1");
        return std::nullopt;
    }

    return opt;
}

int main(int argc, char *argv[]) {
    Magick::InitializeMagick(*argv);

    const auto opt = parse_cli(argc, argv);
    if (!opt)
        return 1;

    fs::create_directories(opt->output_dir);
    const fs::path tmp_dir = opt->output_dir / ".tex_convert_tmp";
    fs::create_directories(tmp_dir);

    std::vector<fs::path> jpg_paths;
    std::vector<SourceFile> sources;

    for (const auto &entry: fs::directory_iterator(opt->input_dir)) {
        if (!entry.is_regular_file())
            continue;
        std::string ext = entry.path().extension().string();
        std::transform(ext.begin(), ext.end(), ext.begin(),
                       [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
        if (ext == ".png") {
            sources.push_back({entry.path(), entry.path(), SourceKind::k_png});
        } else if (ext == ".jpg" || ext == ".jpeg") {
            jpg_paths.push_back(entry.path());
        }
    }

    info("input:       {}\noutput:      {}\njobs:        {}\nPNG files:   {}\nJPG files:   {}\nnormal-mode: {}",
         opt->input_dir, opt->output_dir, opt->num_jobs, sources.size(), jpg_paths.size(),
         opt->normal_mode ? "on" : "off");

    std::atomic<uint32_t> success_count{0};
    std::atomic<uint32_t> failed_count{0};

    if (!jpg_paths.empty()) {
        info("[ JPG -> PNG ]");

        std::vector<std::future<JpgConvertResult>> futures;
        futures.reserve(jpg_paths.size());
        for (const auto &jpg: jpg_paths)
            futures.push_back(std::async(std::launch::async, jpg_to_png, jpg, tmp_dir));

        for (size_t i = 0; i < futures.size(); ++i) {
            auto result = futures[i].get();
            if (result.error_msg.empty()) {
                info("  \u2713 {} -> {}", jpg_paths[i].filename(), result.source.path.filename());
                sources.push_back(std::move(result.source));
            } else {
                error("  [err] {}: {}", jpg_paths[i].filename(), result.error_msg);
                ++failed_count;
            }
        }
    }

    if (!sources.empty()) {
        info("[ PNG -> KTX2 ]");

        const size_t n = sources.size();
        for (size_t i = 0; i < n; i += opt->num_jobs) {
            const size_t batch_end = std::min(i + static_cast<size_t>(opt->num_jobs), n);
            std::vector<std::future<bool>> batch;
            batch.reserve(batch_end - i);

            for (size_t j = i; j < batch_end; ++j) {
                batch.push_back(std::async(std::launch::async, [&, j]() {
                    return convert_to_ktx2(sources[j], opt->output_dir, opt->normal_mode);
                }));
            }

            for (auto &f: batch) {
                if (f.get())
                    ++success_count;
                else
                    ++failed_count;
            }
        }
    }

    fs::remove_all(tmp_dir);

    const uint32_t total = success_count + failed_count;
    if (failed_count > 0)
        info("done - {}/{} succeeded, {} failed", success_count, total, failed_count);
    else
        info("done - {}/{} succeeded", success_count, total);

    return failed_count > 0 ? 1 : 0;
}
